feat: stop sound test
ExpTechTW/DPIP pull request #214
Opened 2024-07-28 13:00 UTC by lowrt

## 這是什麼類型的 PR？

> 選擇所有符合的項目

- [ ] 重構
- [x] 新功能
- [ ] 錯誤修復
- [ ] 最佳化
- [ ] 技術文件更新

## 描述

播放時stop icon可以停止

## 相關 issue

- 相關問題 #
- closes #

## QA 指南、截圖、錄像

### UI 無障礙清單

> _如果您的 PR 包含 UI 更改，請使用此清單：_

- [ ] 變數名稱實現語意化命名？
- [ ] 測試通過 AA 顏色對比？

2024-07-28 15:06 UTC, cracks666666 approved these changes

2024-08-02 05:19 UTC, kamiya10 commented
要不要把 trailing icon 依 `isPlaying` 更改顯示

2024-08-05 08:23 UTC, kamiya4047 requested changes

2024-08-05 08:23 UTC, kamiya10 commented on lib/widget/settings/sound/sound_list_tile.dart
> +  static String? currentlyPlayingFile;
這裡用 `static` 有特殊的原因嗎?

2024-08-05 08:23 UTC, kamiya10 commented on lib/widget/settings/sound/sound_list_tile.dart
> +    if (currentlyPlayingFile == widget.file) {
這裡的 `AduioPlayer` 只會播放 `widget.file` 檔案，不會有其他檔案
檢查是不是正在播放用 `audioPlayer.state == PlayerState.playing`

2024-08-26 20:22 UTC, closed without merging