feat: app country name
ExpTechTW/DPIP pull request #276
Opened 2024-09-13 05:51 UTC by lowrt

## 這是什麼類型的 PR？

> 選擇所有符合的項目

- [ ] 重構
- [ ] 新功能
- [ ] 錯誤修復
- [ ] 最佳化
- [x] 技術文件更新

## 描述

app名稱語言

## 相關 issue

- 相關問題 #
- closes #

## QA 指南、截圖、錄像

![截圖 2024-09-13 下午1 47 26](https://github.com/user-attachments/assets/4aee5445-ad6a-4a33-b637-5ad1f6028b16)![截圖 2024-09-13 下午1 48 05](https://github.com/user-attachments/assets/e9a6a4aa-c233-41d9-a518-a056bb4d45d1)

### UI 無障礙清單

> _如果您的 PR 包含 UI 更改，請使用此清單：_

- [ ] 變數名稱實現語意化命名？
- [ ] 測試通過 AA 顏色對比？

2024-09-13 10:48 UTC, kamiya10 commented
Android 應該可以一起弄

2024-09-13 15:53 UTC, charlie112787 approved these changes

2024-09-14 03:06 UTC, kamiya10 requested changes

2024-09-14 03:06 UTC, kamiya10 commented on android/app/src/main/res/values-ja/strings.xml
> +    <string name="app_name">DPIP 防灾</string>
```suggestion
    <string name="app_name">DPIP防災</string>
```

2024-09-14 03:06 UTC, kamiya10 commented on ios/Runner/ja.lproj/InfoPlist.strings
> +"CFBundleDisplayName" = "DPIP 防災";
```suggestion
"CFBundleDisplayName" = "DPIP防災";
```

2024-09-14 03:06 UTC, kamiya10 commented on ios/Runner/en.lproj/InfoPlist.strings
> +"CFBundleDisplayName" = "DPIP DisPre";
```suggestion
"CFBundleDisplayName" = "DPIP";
```

2024-09-14 03:06 UTC, kamiya10 commented on android/app/src/main/res/values-en/strings.xml
> +    <string name="app_name">DPIP DisPre</string>
```suggestion
    <string name="app_name">DPIP</string>
```

2024-09-14 03:19 UTC, kamiya10 approved these changes

2024-09-14 03:23 UTC, merged