Fix/magnitude text
ExpTechTW/DPIP pull request #51
Opened 2024-04-19 15:51 UTC by kamiya10

ios is untested
android at max font size
![image](https://github.com/ExpTechTW/DPIP/assets/58339640/afe930f3-66c2-43bd-aa7e-b44d3d1f08cb)
normal
![image](https://github.com/ExpTechTW/DPIP/assets/58339640/b346837e-9030-4870-9f45-464cad8f4083)

2024-04-19 15:55 UTC, yayacat approved these changes

2024-04-19 23:54 UTC, lowrt requested changes
報告列表炸裂
![螢幕擷取畫面 2024-04-20 075301](https://github.com/ExpTechTW/DPIP/assets/37591855/81ac4279-057e-47d3-939b-698587d77a87)

2024-04-20 05:13 UTC, whes1015 approved these changes

2024-04-20 05:14 UTC, whes1015 approved these changes

2024-04-21 03:59 UTC, kamiya10 commented
@lowrt review

2024-04-21 05:50 UTC, lowrt approved these changes

2024-04-21 05:50 UTC, merged

2024-04-21 06:03 UTC, lowrt reviewed
IOS版本只能排在1.2.3了