Fix: eew screen display
ExpTechTW/DPIP pull request #66
Opened 2024-04-24 15:46 UTC by lowrt

2024-04-24 16:41 UTC, yayacat approved these changes

2024-04-24 16:43 UTC, kamiya10 requested changes
Android 的部分有改嗎
還是不需要

2024-04-24 16:43 UTC, kamiya10 commented on lib/view/earthquake.dart
> +                        const SizedBox(height: 1),
```suggestion
```

just delete it :3

2024-04-25 00:39 UTC, lowrt commented
> Android 的部分有改嗎 還是不需要

看起來要改XD

2024-04-25 02:40 UTC, kamiya10 commented
給個 Android 截圖

2024-04-25 02:59 UTC, cracks666666 commented
eew 截圖?  要老人化嗎？

2024-04-25 03:13 UTC, cracks666666 commented
![Screenshot 2024-04-25 110924](https://github.com/ExpTechTW/DPIP/assets/95209282/e5abf109-6e31-4868-86bc-2b993ae81b73)
![Screenshot 2024-04-25 111224](https://github.com/ExpTechTW/DPIP/assets/95209282/3ac7bd56-73b9-4971-840c-f4352faeff8a)
![Screenshot 2024-04-25 111207](https://github.com/ExpTechTW/DPIP/assets/95209282/97a39aa7-1aed-410c-8d22-eff564907743)
不太對 .....

2024-04-25 03:18 UTC, cracks666666 commented
![Screenshot 2024-04-25 111827](https://github.com/ExpTechTW/DPIP/assets/95209282/4f47a9e0-6d8a-41ae-b2d3-bed0dab91ba6)
修好 🆗

2024-04-25 03:25 UTC, cracks666666 commented
![image](https://github.com/ExchTW/DPIP/assets/95209282/126d0ad4-11ab-4e1e-a898-9a4cf924fed4)
大號版 🆗

2024-04-25 07:45 UTC, kamiya10 approved these changes

2024-04-25 07:47 UTC, merged