fix: ios depth
ExpTechTW/DPIP pull request #78
Opened 2024-05-09 10:03 UTC by lowrt

![SNYnhNA](https://github.com/ExpTechTW/DPIP/assets/37591855/a40b63c8-175e-41d0-be33-71710b8d79c8)

2024-05-11 23:44 UTC, yayacat approved these changes

2024-05-12 16:08 UTC, kamiya10 commented
如果這樣顯示比較好的話
Android 也可以順便

2024-05-13 23:31 UTC, lowrt commented
@kamiya10  可以 Review 了
我有加一些修正問題，請過目

2024-05-17 07:47 UTC, kamiya10 requested changes

2024-05-17 07:47 UTC, kamiya10 commented on lib/view/report.dart
> +                                          ? CupertinoColors.black : CupertinoColors.white,
```suggestion
                                      color: CupertinoColors.secondaryLabel.resolveFrom(context),
```

2024-05-17 07:47 UTC, kamiya10 commented on lib/view/report_list.dart
> +              ),
這裡之後如果有實裝無限捲動的話
可能會需要改成 builder
不然效能會出事

2024-05-17 07:47 UTC, kamiya10 commented on lib/view/report_list.dart
> +                    ? Center(
```suggestion
              if (showRetryButton)
                SliverToBoxAdapter(
                  child: Center(
```

2024-05-17 07:47 UTC, kamiya10 commented on lib/view/report_list.dart
> +                    : const SizedBox(),
```suggestion
```

2024-05-17 07:47 UTC, kamiya10 commented on lib/widget/earthquake_report_list_tile.dart
> +                    : CupertinoColors.white,
```suggestion
                color: CupertinoColors.label.resolveFrom(context),
```

2024-05-17 07:48 UTC, kamiya10 commented on lib/view/report_list.dart
> +              ),
現在是還沒關係
如果要之後再改的話就把這串標成已解決就行

2024-05-17 08:31 UTC, lowrt commented
@kamiya10 已解決

2024-05-17 15:32 UTC, kamiya10 commented
給個最新截圖

2024-05-17 16:20 UTC, lowrt commented
@kamiya10 
![螢幕擷取畫面 2024-05-18 002002](https://github.com/ExpTechTW/DPIP/assets/37591855/ff5600e9-fb24-4c11-ae3a-e16242818448)
![螢幕擷取畫面 2024-05-18 002018](https://github.com/ExpTechTW/DPIP/assets/37591855/5aafc483-4682-4938-a6e1-5277d4b1a6ec)

2024-05-17 18:07 UTC, kamiya10 requested changes

2024-05-17 18:07 UTC, kamiya10 commented on lib/view/report.dart
> +                                      color: CupertinoColors.secondaryLabel.resolveFrom(context),
```suggestion
                                      color: CupertinoColors.label.resolveFrom(context),
```
把這個改成亮一點的 label 感覺會比較好

2024-05-18 08:30 UTC, kamiya10 approved these changes

2024-05-18 08:30 UTC, merged