feat: home page
ExpTechTW/DPIP pull request #87
Opened 2024-05-26 18:58 UTC by Yoyochou0901

2024-06-11 10:41 UTC, kamiya10 requested changes
run formatter

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_air.dart
> +  final double usepaindex;
```suggestion
  final double usePaIndex;
```
駝峰命名

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_air.dart
> +  final double gbdefraindex;
```suggestion
  final double gbDefraIndex;
```
駝峰命名

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_air.dart
> +class weatherAir {
```suggestion
class WeatherAir {
```
類別要用 TitleCase

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_feel.dart
> +class weatherFeel {
```suggestion
class WeatherFeel {
```
類別要用 TitleCase

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_gust.dart
> +class weatherGust {
```suggestion
class WeatherGust {
```
類別要用 TitleCase

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_precip.dart
> +class weatherPrecip {
```suggestion
class WeatherPrecip {
```
類別要用 TitleCase

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_pressure.dart
> +class weatherPressure {
```suggestion
class WeatherPressure {
```
類別要用 TitleCase

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_realtime.dart
> +class weatherRealtime {
```suggestion
class WeatherRealtime {
```
類別要用 TitleCase

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_temp.dart
> +class weatherTemp {
```suggestion
class WeatherTemp {
```
類別要用 TitleCase

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_vis.dart
> +class weatherVis {
```suggestion
class WeatherVisibility {
```
類別要用 TitleCase
不要縮寫

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_realtime.dart
> +  /// 天氣體感溫度
```suggestion
  /// 能見度
```

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_realtime.dart
> +  final double isday;
```suggestion
  final double isDay;
```
駝峰命名

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_wind.dart
> +class weatherWind {
```suggestion
class WeatherWind {
```
類別要用 TitleCase

2024-06-11 10:41 UTC, kamiya4047 commented on lib/model/weather_wind.dart
> +  final String dir;
```suggestion
  @JsonKey(name: 'dir')
  final String direction;
```

2024-06-11 10:41 UTC, kamiya10 commented on lib/util/dist_code.dart
> +    }
async 裡面不需要用 try catch
讓錯誤 bubble 到最上層 sync 再做錯誤處理

2024-06-11 10:41 UTC, kamiya10 commented on lib/util/dist_code.dart
> +  }
沒有意義
直接 `var zipCode = data[key];` 會比多血一個 function 簡潔

2024-06-11 10:41 UTC, kamiya10 commented on lib/view/me.dart
這個應該放在另一個 PR

2024-06-11 10:41 UTC, kamiya10 commented on lib/view/home_page.dart
> +class TempColor {
```suggestion
class TemperatureColor {
```
Temp 通常會指暫存 temporary 的意思
溫度直接把 Temperature 寫出來會比較好

2024-06-11 10:41 UTC, kamiya10 commented on lib/view/home_page.dart
一個 widget 檔案只能包含一個 `StatefulWidget` 或 `StatelessWidget` 來避免 import 混淆
把其他的 Widget 放到 `lib/widget/` 底下

2024-06-11 10:41 UTC, kamiya10 commented on lib/view/home_page.dart
> +  Color getColorForTemp(double temp) {
```suggestion
  Color getTemperatureColor(double temperature) {
```
Temp 通常會指暫存 temporary 的意思
溫度直接把 Temperature 寫出來會比較好

2024-06-11 10:41 UTC, kamiya10 commented on lib/view/home_page.dart
> +}
要取得幾 % 的空間可以直接用 Flex 搭配 Flexible 的 flex 
`MediaQuery.of().size` 呼叫的時候只要 `MediaQuery` 裡面的屬性有變更就會 rebuild 一次 widget tree
可能會有效能疑慮

2024-06-14 02:43 UTC, kamiya10 approved these changes

2024-06-15 16:22 UTC, yayacat approved these changes

2024-06-15 16:22 UTC, merged