原本
ExpTechTW/DPIP pull request #96
Opened 2024-06-16 05:22 UTC by charlie112787

2024-06-16 08:09 UTC, lowrt requested changes
🧐

2024-06-18 23:55 UTC, lowrt submitted a review, later dismissed

2024-06-19 00:01 UTC, lowrt submitted a review, later dismissed

2024-06-20 01:35 UTC, Timyaya approved these changes

2024-06-20 03:31 UTC, whes1015 approved these changes

2024-06-20 09:49 UTC, kamiya10 requested changes

2024-06-20 09:49 UTC, kamiya10 commented on lib/view/notify.dart
> +  Widget buildSoundButton({
移到獨立的 Widget

2024-06-20 09:49 UTC, kamiya10 commented on lib/view/notify.dart
> +  Widget buildPlayButton(String soundPath) {
移到獨立的 Widget

2024-06-20 09:49 UTC, kamiya10 commented on lib/view/notify.dart
> +  Widget buildTitleText(String text) {
移到獨立的 Widget 或直接寫在 build() 裡面

2024-06-20 09:49 UTC, kamiya10 commented on lib/view/notify.dart
> +    const String otherTitle = "其他音效";
放到最上層或直接把值寫在 widget 裡面

2024-06-20 13:29 UTC, kamiya10 approved these changes

2024-06-20 15:20 UTC, lowrt approved these changes

2024-06-20 15:20 UTC, merged